server:
  port: 9090

bot:
  name: MainInsiderBot
  token: 7949198317:AAGuJI6KwUHseDJ5yoAHQ76_cFu2baFuL0c
  owner:
cron:
  # cек., мин., день, неделя, месяц, год
  # первая цифра 0 значит, что каждую минуту и 0 сек
  scheduler: 0 * * * * *


spring:
  application:
    name: mainBot
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:6432/main-bot-db
    driver-class-name: org.postgresql.Driver
    username: user
    password: user